apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: ack-system
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:LO3t375DPJcnCMVcmDEGQwd6yOwOcUlp9l1R8qQ8tS6q6jdXwxFGZi4zCwakvpREb2bUUDpJd9UM1a7PN3mo4o4pC5Y621Y4LMRiYHuCwi6nh68gpG4FzA0a1Y8cBODMwZIeKcTFY+ai4lAfV8+nblR6ktZgXTARup2iZbwcgNDggKPnNvgd,iv:zgZquTw1cdhPkxrK+kBP9qyyQdwJrpVQoyGiYqgY9a4=,tag:XEq5hihFWShjGfHmVNiWLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVENPa3JWKzFhbk92MXFB
            emZZYzFaaFB4Q2tCcm11eEFTSmNyY0xUQVVnCnJ1cndnUFNWeXlLY0hPak96Z2Z5
            V3FwN0Q3RkNTQ0ZnZ3ZURGdjMDBTWWcKLS0tIDAza0syK2IzcXFIRzNzclRPOW9U
            L3ZWUlo1Q2ZRVTJKK1doL2tmNmZ5QmcKcPg8qhEMhcU8/fF1rgvejKNV7cyAn78i
            4jtNiBdGxk9pqeAdcBVEJqfHZGLRMXruB4hH2PppdLDR5D+gt99pww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1amqtgevmdxutg07rkr3wggua43620zgncgfq53vkww0283wrgspqv9q0jw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T12:24:08Z"
    mac: ENC[AES256_GCM,data:2/bWlER9WHqmcQG/XeT1zYBB5UpjrUb6D3wfIoIM1xtjWK3utzcgodZtH/8WhBWf8jTEMRqYeDWhgopgbJItdsKPpDH3hTaMm3xKs3w3nJgYUpV7br8xvW6kdAwdg+DkzxEurUoTXye61x3u7mZJRKfV7cPUWrD8mB03DFYsZWM=,iv:TTly/yVBuw9bguiwqAcHWw1/F4zG++KhfGkmaUH9unM=,tag:JopmVbRgz5qsciUJ4b9tSw==,type:str]
    version: 3.13.1
