apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: capa-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:87zsQxNzsrFOj9psKd905yvBxABjnVENO7wDqqRVunKK2miUF2hoNHxlOyKZpidxRT0QIw==,iv:iyqgpeXvSWGAEVzjAxKAvW9fWGtQfTYZ0DToneUfBcg=,tag:4PY3P/MqPKSsS+n4gnjVgQ==,type:comment]
    #ENC[AES256_GCM,data:fkD4m1p94FFuwvQyRP9jj/Ff1XEI0sVVsVLrNiOu4rByEvw/4bnimQybUy6Iqj/WOgfTCaayD2c=,iv:TtYuMHyv6hFROdEjEQ9enhN4DVhEnApfgm/8/Zj3jIc=,tag:FU335soKVVfwUEohAqMTSg==,type:comment]
    #ENC[AES256_GCM,data:MLljOWEJyz+reOjVKjJEzZd1r8GJcZ+OHuWM/RbKCZoRncZnGVWMFKCA9IE7yOSyal+9a07hOl9hZTtdhCkETFfTUx61EDL3MFk=,iv:bGerbnGE4dMZ1d30xFXelLI0hg78mRYJ92BTg21a7PY=,tag:Q5VyRxVxM/F+7cHEBk9RAA==,type:comment]
    #ENC[AES256_GCM,data:r7p35IrVoYdwqfGgbLuZbSGAAd4Z4DRcfMoKtWFM3eaE3aMw8pU6sVAQOEC95HyQ2W9j9ri8ve93ZeUD8ks8CFSz+gVg7xuzbUJgqm6Cv2sqYfl6E+kX,iv:zzxswuOYML2mEvsNcde51erOb0bnPrRQykzmDo9gfIU=,tag:LND8y47qNCDsgjSgsWEIMQ==,type:comment]
    AWS_B64ENCODED_CREDENTIALS: ENC[AES256_GCM,data:CgsXKob9SP1nxKWHY7ItBN70Rm8CWLXUAzPtDggR+YgqxtXm10r+,iv:GgAFEVloeflMwE1Y2gJvR6dd7x6brFrDJISwdlJasgA=,tag:+lH/wF1307J8tTqY6eKVGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQXkrM0p5aVgvMTlBaUkw
            WkVFTytxOEsxK2QyVmhIRmlOV3JoaTkxdGtrCnd3RmVsU0tUWFdFNjlsRnV5RE96
            cEF2N1ZUWitJWHNmM0xsZTh2Sy9WNnMKLS0tIHFZalIwYlNyekRpd2NLc28xVmhC
            M1ZwaHhNUWVBUXRiYnh5enQzazZMSUkKgQ/1rBPV2m0gQ5RYhgR4vHtCDzcG6A3n
            e/kbIeGVGUMY/oBwDlyDS3K9lNWoNYBQdXbYDTpEtWwKPvCl2qZNaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18lcxc28qak3y4ssreqln7lpzt04ddfh5pavnwglnpxe8et2s4pvqyw25yt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:42:33Z"
    mac: ENC[AES256_GCM,data:Xg9MiTJyIVNZZax73UUsWJG24/grA3Awhre8DdXzb13Gk8R+kt3h3fEEPaWhonobV7XxGB2f7fMQOk7M7rkadESoihGn9HMX7lHpiuV2logQ2XY57HH8F7cz+2vaMvEPoQBuJbspBJdckLhR+t1sGxbXJ5q3JVYuGml+n18yx1w=,iv:CScwj10IkUNFoG/Z2HjE17uHf1EIKJeC3SGoMfwdx2k=,tag:ilMW3kI29SNKasq/In7B1A==,type:str]
    version: 3.13.1
