apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: capa-system
type: Opaque
stringData:
    AWS_B64ENCODED_CREDENTIALS: ENC[AES256_GCM,data:tHfBOgWaZFJpuZVBSyl+hj5anKA6qGkSA3whxoZwcUx6hsyuNicx4eJu4J4hBUsysv1Qoi7AmoYvBXnHjsyJsFIXWRAY4OnKj6QaXSgvEEg4YmtFQ5fU9E4hnXbhlAV+KohJJiCUoaiOlzLXghmcAWfaGCWMkGMT/mKo3yLZlCSEDINR6GCumaBfGc1O3KeS/S3PbGpZA/GyG/okzLaWAflntlGVVcTCuvdjd0zowu9H+o/uk1dPfw==,iv:f263ddlspmBm4Nvho8ejaKT8LZv4hO9gbFoy7NW2ulw=,tag:I4Vcf9SAvDsRRiWa6OTMBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraTVWdWQwM1dOSzBTc3hh
            YW05cmp6UkR3YS9lZkZzdE1lcWFKcWtPSHk0Ck1TTGR6WkpDdFRWRWlleVM4NDln
            TUUreWVjT2gwNjA5ZFlidEV6bnZpMHcKLS0tIHZ4OTN0d0JNY1V0NGgxbjR4RDJs
            bjRhbU01dVNxK3RoaWtBRm45VDkzZnMKgwLmc9NrXv1Udruyr6dNyaHffJV65VZO
            UlVKDXbL4B0sVVF51qb5tAOlc3LOwoRx9C86Z6G6FSaDfhMVor0cWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1amqtgevmdxutg07rkr3wggua43620zgncgfq53vkww0283wrgspqv9q0jw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T14:57:56Z"
    mac: ENC[AES256_GCM,data:yMSOhVgvGjkt2y4fgZZwbmB9uCfAPXIFmBjNzR5Dd3LmqZir35/X1oxnWxYrKbHkbj0YKHjQIyJ6cYPuHcQ6qATUb7ObOMp3cj7Qe9zuiAdkFKLK1dtZISYzH8LCtPomd8yfj2tfwORN9MB3ElTxKQw/jtQouXfRYjCZRAqxR2U=,iv:UJeDxdT9rnWE4kJChAdRrexaQiooAHOBDKmKhjY+viE=,tag:x8Jm1CY3ROjwtWf3sWeo9g==,type:str]
    version: 3.13.2
