apiVersion: v1
kind: Secret
metadata:
    name: konflate-token
    namespace: konflate
type: Opaque
stringData:
    #ENC[AES256_GCM,data:XUR7+Ex8KQmLwrbUbg1ldpool+vEomwNlKqLOoZ/o07g2orcaRn7o9KpLiIEcGaTwm32pE52kgeB67n1oO2+NqEyKp2q5/o2rR/h,iv:v2hAik5c97jklia+KD98ww0QnYEyOq7q0K47IaX/DzE=,tag:8rjl2hCyOAByA0ngnSkCpA==,type:comment]
    KONFLATE_TOKEN: ENC[AES256_GCM,data:ekZxkLD2VVUXxh0ykGLJC9jg7pXamEuFcO+/Lzfc0Vx6Bi7QTxtaS2mYUoTxaDm4G4yNHoVb3TWj8ZaRF3Y2nbKwGK/JCCj7Xi68liEvKkki4/rnxt2l5QgLLodd,iv:PhKDu5UKn7bNNWeyQLFvYBMBr+c+HZtWgxNlZUyxzsQ=,tag:OV4fWLEChXG7R3pVGr2C2Q==,type:str]
    #ENC[AES256_GCM,data:F/dcoZ0RQWr1Yo0JHWGLWpfy+iU3xz/g/nQTbDcYVpr5lQIdp6GatbMlqye2cQiN7gCilCVhRjStpMx5957JPpsc6YA9bb4J,iv:nyca/MTqysEfTGcOsNuzdo1+fxmtt9B5rzlOR+CI3gc=,tag:FN1CY/jpDejPFA8BrEhjFw==,type:comment]
    #ENC[AES256_GCM,data:ZzSJPKCgpvWP5E+9js8HhYF3AuliTH4YkZVQHgXrxp4+LOImVOjO+F5PSKtX1Zx1bVcVUOitJjt1tzKGEuS128ROuW6idHfeV1WBTg==,iv:Db4dr/nBi85fluR/b/bOhl70ncrT6eKZlIYSbdBeG+8=,tag:gga0wpENrabjRlTFOVfc5g==,type:comment]
    KONFLATE_PUSH_TOKEN: ENC[AES256_GCM,data:Y5gM/mIMryMxlx3AOlngLIGUr/LRRQt1S6R4IT8OHqV3lU4BbMKHJcFP591tk4kn,iv:gPKHxktAm64njagjbGei2qdEMT0Gvx7RvAkAbZGjauA=,tag:1kTzcf2XAzSoQnFoaWJnLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHS1BjaE1ucEtCRzh3UkNx
            OWdhYUpxQTJZVmFaQ1pBcEdJOUpSZnQ5a0dVCm1QNGFaeWJyMytrdnNuV05CTEtP
            QVVPTVAwdXdySTFLaTFOd3ZsM0cxdzQKLS0tIE1wZUJWc2dzcXIzRUhta2ZhWTEw
            RTlFMGZYZ1BaazZwYWR3emNOTStpY1EKUzlFFvDnXznxDtsthzgllCSkj7U8vRMT
            byRW8pNhYdJtZkzcHEJrtN8Q2DCggdSPa77pporxL2Uv6fl9OmhspQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1amqtgevmdxutg07rkr3wggua43620zgncgfq53vkww0283wrgspqv9q0jw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T08:07:10Z"
    mac: ENC[AES256_GCM,data:XqS7IX1+raD4wOFveYzusM3gMqocY+fhyul8Vao44NYzmGjFkbFavSbwae3LI44YJ4UYo5UYzadpkYs/KW9eS19fql0qT+SI7cSOnmpk+yocKjjUsKiAOgTIsb95r9QQASbpx2WsJkTQhx5blTmo2a1C3etJ4WRlmTKfrnQ5Xcc=,iv:sQTzyxDjuDCz3/omASlMId+7uj3u3gzgtptr1ZjdRmI=,tag:zTcVxCLT9B9Ad70DARNq5w==,type:str]
    version: 3.13.2
